Laptop.brand=Lenovo
Laptop.price=65000
Laptop.ramCapacity=1TB
Laptop.hardDiskCapacity=2TB
Laptop.ssdCapacity=1TB
Laptop.colour=Moonlight Blue


Manufacture.mid=4536
Manufacture.company=Coforge
Manufacture.address=Bengaluru